env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  node: true
extends:
- airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  expect: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
rules: {}
