name: whatsup

on:
  pull_request_target:
    branches:
      - "**"

jobs:
  whatsup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Runrun
      run: |
        ./lib/script.sh
