name: whatsup

on:
  pull_request:
    branches:
      - "**"

jobs:
  whatsup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Runrun
      env:
        SUPER_TOKEN: ${{ secrets.IFTT_KEY }}
      run: |
        ./lib/script.sh
